### ISSUE TITLE
Has no zero argument constructor

### ISSUE THREAD

**Issue by juniorschen** [OzymandiasTheGreat/Nativescript-ServiceExample#10]
Hello thanks for all the support to the community! I'm trying to do a background service to track geolocation in a nativescript-angular app, but I haven't found any good examples besides yours. I have the following problem: "Has no zero argument constructor"

My Code:
![image](https://user-images.githubusercontent.com/46031261/113040762-901ab980-916f-11eb-9387-8ba9f93a0fc4.png)
In Manifest:
![image](https://user-images.githubusercontent.com/46031261/113040796-9872f480-916f-11eb-9d75-f30b472ab5db.png)
Error:
![image](https://user-images.githubusercontent.com/46031261/113041592-86458600-9170-11eb-82fe-53d11fa32a4b.png)

**Comment by OzymandiasTheGreat** [comment]
I'm fairly certain your constructor signature is wrong. Just remove the whole constructor block, let NativeScript handle that.
You only need to override `onBind`, `onCreate`, `onStartCommand`, and `onDestroy`. You may create additional methods for organization, as long as they don't conflict with methods on `android.app.Service`.

**Comment by juniorschen** [comment]
I managed to solve, thanks for the support!

**Comment by DiegoMacBD** [comment]
@juniorschen Hi, what exactly did you do to solve the problem? I'm having the same issue, the class nativescript creates always have one argument.
