### ISSUE TITLE
Background service 

### ISSUE THREAD

**Issue by Zmast1private-Ltd** [OzymandiasTheGreat/Nativescript-ServiceExample#3]
It is working nicely ,it prints "Ping" msg based on the timer i set,but the problem is, if i use some services Example- apple healthkit related functionalities we cant able to use the imported libraries instead it throwing undefinesd class error,but i correctly imported the healthdata service ,so it wont consider any other libraries from this service ..any help?

**Comment by OzymandiasTheGreat** [comment]
That's entirely insufficient information. Could you post the entire error message?

To be honest, I've experienced quite a few undefined class errors with NativeScript, not on this project but still they are terribly hard to debug. First thing I'd try is changing marking mode. The changes in latest versions of NativeScript cause quite a few of these errors with code that worked fine in earlier versions, so if performance is not critical for your application, simply changing marking mode could fix this bug. 

Then again, it could be something else, hard to tell without error log. Depending on the error could be hard to tell with error log too.

Sorry, couldn't be of more help.

**Comment by Zmast1private-Ltd** [comment]
if (!this.timerId) {
            this.timerId = setInterval(() => {
                console.log("PING");
                this.getHealthData("steps", "count");
            }, 5000)
        }

getHealthData(dataType, unit) {
        let options =
        {
            startDate: new Date(),
            endDate: new Date(),
            dataType: dataType,
            unit: unit,
            // aggregateBy: "day",
            sortOrder: "desc"
        }
        console.log(JSON.parse(JSON.stringify(options)));
        firebaseWebApi.database().ref("/googlefit").child("14").set("125")
          .then(() => {
            console.log("Value added");           
          })
          .catch(error => console.log("firebase value add Error: " + error));
        this.healthData.getHealthQuery(options).then(result => {
            this.zone.run(() => {
                this.dataSet = result;
                console.log(dataType + ": " + this.dataSet);
            });
            for (let i of this.dataSet) {
                i.start = i.start.toISOString();
                i.end = i.end.toISOString();
            }
            console.log(this.dataSet);
        })
            .catch((err) => {
                console.log("Error while querying data: " + err);
            })
    }



This is my code ,the data gets stored in firebase successfully for every 5 seconds,,,,but the healthdata.gethealthquery depends on a separate service provided by healthdataservice i used in my project. so i got an error as undefined gethealthquery
![Screenshot (14)](https://user-images.githubusercontent.com/73389460/97103225-1a4a8780-16d1-11eb-9c9b-259e555f2f88.png)
![Screenshot (15)](https://user-images.githubusercontent.com/73389460/97103229-1c144b00-16d1-11eb-9baa-30aeac9f4412.png)
![Screenshot (16)](https://user-images.githubusercontent.com/73389460/97103230-1c144b00-16d1-11eb-8064-5259723120d9.png)

**Comment by OzymandiasTheGreat** [comment]
Ah, this simpler.

Wouldn't it be okay to just check if healthdata is defined and if it's not store nothing and wait for another iteration when it's actually defined?

Coordinating services is hard, but it's a bit beyond the scope of this project.

**Comment by Zmast1private-Ltd** [comment]
thank you OzymandiasTheGreat i got the output as per our requirements,

how to show the push notifications message dynamic in setcontenttext(text)

**Comment by Zmast1private-Ltd** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/73389460/97294268-c9bf5f80-1873-11eb-8c36-db1863f5af21.png)

this.newdata = 144;
i used  builder.setcontenttext(this.newdata.tostring());
I got the value 144 , how can i show in push notifications as      "New data added 144"??

**Comment by OzymandiasTheGreat** [comment]
Hm, that depends. You're using firebase which has it's own mechanisms for push notifications.
However if you want to show a local notification, with results from server polling you could do something like this

 ```
const NOTIFICATION_ID = 12;
const CHANNEL_ID = "playback";
const CHANNEL_NAME = "Playback Notifications";
const CHANNEL_DESC = "Now Playing Notifications";
const notificationManager = this.getSystemService(android.content.Context.NOTIFICATION_SERVICE);
if (platform.device.sdkVersion >= "26") {
	let mChannel = notificationManager.getNotificationChannel(CHANNEL_ID);
	if (mChannel === null) {
		mChannel = new android.app.NotificationChannel(
		        CHANNEL_ID,
			CHANNEL_NAME,
			android.app.NotificationManager.IMPORTANCE_LOW,
		);
		mChannel.description = CHANNEL_DESC;
		notificationManager.createNotificationChannel(mChannel);
	}
}

const builder = new androidx.core.app.NotificationCompat.Builder(this, CHANNEL_ID);
const intent = new android.content.Intent(this, (<any> com).tns.NativeScriptActivity.class);
const pendingIntent = android.app.PendingIntent.getActivity(this, 0, intent, 0);

builder
	.setContentTitle(title)
	.setContentText(artist)
	.setSmallIcon(util.ad.resources.getDrawableId("mdi_play_pause"))
	.setContentIntent(pendingIntent)
	.setVisibility(androidx.core.app.NotificationCompat.VISIBILITY_PUBLIC)
notificationManager.notify(NOTIFICATION_ID, builder.build());
```
You gotta do this within the service object, as "this" refers to background service.

**Comment by OzymandiasTheGreat** [comment]
I'm closing this since there doesn't seem to be an issue.
