### ISSUE TITLE
Autostart not recognized

### ISSUE THREAD

**Issue by theremon** [OzymandiasTheGreat/Nativescript-ServiceExample#5]
Hi
this is more of a support question than an issue.
I'm trying to implement this in a project and I'm having problems with the autostart service.
I've made several attempts, but keep getting an error that the autostart class cannot be found - the error goes like this:
`java.lang.RuntimeException: Unable to instantiate receiver org.proj.name.Autostart_Receiver: java.lang.ClassNotFoundException: Didn't find class "org.proj.name.Autostart_Receiver" on path:... `
Do  you have any pointers on how to fix this?
Thanks

**Comment by OzymandiasTheGreat** [comment]
The first thing that comes to mind is - are you using the new `@NativeClass()` descriptor? Altho, if you aren't, you should be getting more errors I guess.

**Comment by theremon** [comment]
Hey there
thanks for the reply.
I had a package name wrong (it had a typo). I fixed it and now it's working.
Thanks again!
