### ISSUE TITLE
NS7 problems

### ISSUE THREAD

**Issue by theremon** [OzymandiasTheGreat/Nativescript-ServiceExample#6]
Hi there Tomas

I have a question for you...

while trying to upgrade my project from NS 6.5.3 to NS 7, there are some issues referencing the 'android' object.
For example, I got this code:

```
@NativeClass()
class Autostart_Receiver extends android.content.BroadcastReceiver {
  onReceive(context: android.content.Context, intent: android.content.Intent): void {
      const pm: android.content.pm.PackageManager = context.getPackageManager();
```

and these references:
```
/// <reference path="./node_modules/@nativescript/types-ios/lib/ios.d.ts" />
/// <reference path="./node_modules/@nativescript/types-android/index.d.ts" />
/// <reference path="./node_modules/@nativescript/types-android/lib/android/android-declarations.d.ts" />
/// <reference path="./node_modules/@nativescript/types-android/lib/android.d.ts" />
/// <reference path="./node_modules/@nativescript/types-android/lib/android-17.d.ts" />
```

However, the **android** object is not recognized.
Do you have any hints?

**Comment by OzymandiasTheGreat** [comment]
I had similar issues, however, I do not recall how I resolved them. Sorry 'bout that.
A quick fix would be to put this at the top of your service file:
```
declare const android: any;
```
Edit: this may interfere with autocompletion in your editor, which is why it's a quick and dirty fix only.

**Comment by theremon** [comment]
Thanks for the reply Tomas.
Wouldn't re-declaring the constant actually nullify the expected behavior? I mean that it won't show errors in the editor, but then you can't reference `android.content.Context` for instance

**Comment by OzymandiasTheGreat** [comment]
Not at all. You're not actually declaring anything as android, so there's nothing to override the android object. This is just a way to shut up typescript without affecting runtime in any way.
If you provided value for this declaration, then it'd be a whole 'nother story. Just don't do that.

**Comment by theremon** [comment]
Ok, I'll try it out..
Thanks a lot!

**Comment by OzymandiasTheGreat** [comment]
If that worked for you, could you please close this issue?

**Comment by theremon** [comment]
Hi Tomas, sorry for not replying earlier.
It worked, in conjuction with adding the reference.d.ts file in tsconfig.json - it wouldn't read it otherwise...
Thanks a lot for your help!
