### ISSUE TITLE
Angular NativeScript - Class Not Found

### ISSUE THREAD

**Issue by DiogoSilvaEBS** [OzymandiasTheGreat/Nativescript-ServiceExample#7]
Hello,

I am trying to make a service based on this example using Angular NativeScript, but when the application is opened it returns errors like:

> System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
> System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.ContinuousService" not found.

I tried to add the files to the webpack (as shown below) and add "importHelpers: false" to tsconfig.json, but it keeps returning the same error.

> const appComponents = [
>         "@nativescript/core/ui/frame", "@nativescript/core/ui/frame/activity",
>         resolve(__dirname, "src/app/services/background/continuous-service.android.ts"),
>         resolve(__dirname, "src/app/services/background/restart-receiver.android.ts"),
>         resolve(__dirname, "src/app/services/background/autostart-receiver.android.ts")
>   ];

Is there anything missing or do you have any idea what can be done to run the application without this error?

Thank you.

**Comment by OzymandiasTheGreat** [comment]
Are you by chance using NativeScript 7? The article hasn't been updated yet. NS7 introduced `@NativeClass()` decorator, you're supposed to put it above all other class decorators.

**Comment by DiogoSilvaEBS** [comment]
Yes, i'm using NS 7 ("@nativescript/core": "~7.0.0"). So I have to put this decorator `@NativeClass()` above `@JavaProxy('com.tns.ContinuousService')` decorator?

**Comment by OzymandiasTheGreat** [comment]
Exactly. Took me way too long to discover this myself, when I was updating my apps.

**Comment by DiogoSilvaEBS** [comment]
I believe it took time for you to discover that the new decorator solved this error. Now, the application is already running without the error described above. Thank you very much, you saved me and whoever comes across this error too!
